#Base configuration
base:
  url: "http://127.0.0.1:8080"

# Database configuration  
database:  
  # Database name  
  name: "sqlrest"  
  # Database user  
  user: "root"  
  # Database password  
  password: "root"  
  # Database host (IP address)  
  host: "127.0.0.1"  
  # Database port  
  port: 3306  

# Logger parameters  
logger:  
  # Log file path  
  log_filename: "logs/app.log"  
  # Log level (info, debug, etc.)  
  log_level: "debug"  
  # Maximum size of each log file in MB  
  max_size: 10  
  # Maximum number of log files to keep  
  max_backups: 5  
  # Maximum age of log files in days  
  max_age: 28  
  # Whether to compress old log files (true or false)  
  compress: true  
